### PR TITLE
Adding some faces of PHP Internals (including myself)

### PR DESCRIPTION
**Pull request by patrickallaert**
Alphabetically:
- Bob Weinand
- David Soria Parra
- Felipe Pena
- Ferenc Kovacs
- Hannes Magnusson
- Joe Watkins
- Julien Pauli
- Michael Wallner
- Patrick Allaert
- Pierre Joye
- Stas Malyshev

### CODE REVIEW

**Comment by dragoonis** [comment]
Good shout @patrickallaert

**Comment by patrickallaert** [comment]
Thanks @dragoonis ;-)

**Comment by bwoebi** [comment]
That's new news to me that Joe were PHP 5.5 RM o_O

**Comment by dracony** [comment]
Feel free to make a new PR fixing that )

**Comment by bwoebi** [comment]
Nah, I don't care… just noted it as I had a quick spot at it because I got some mention on twitter ;-D

**Comment by patrickallaert** [comment]
@bwoebi @dracony Fixed in PR #12

**Pull request merged**
