### PR TITLE
Remove unnecessary 'small' in url

### PR DESCRIPTION
**Pull request by adrorocker**
🤦  I forgot to remove this

### CODE REVIEW

**Comment by adrorocker** [comment]
This works now!

                                                        ⬇️ 

Screen Shot 2020-08-05 at 5 20 50 PM

**Comment by adrorocker** [comment]
@dracony Hi there, just checking if you would consider merging this PR and possibly deploy it? Thanks in advance. 🤘

**Comment by vanderwooodsen** [comment]
Weird, I thought it was deployed already, will check tomorrow. Thanks for the heads up!

**Comment by dracony** [comment]
Deployed! Thanks!

**Pull request merged**
